"""empty message

Revision ID: 021bb6f183da
Revises: 224ed08eabcd
Create Date: 2020-07-03 15:24:07.311748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021bb6f183da'
down_revision = '224ed08eabcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('max_serving_size', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('min_serving_size', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user_jwts', ['user_jwt_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_jwts', type_='unique')
    op.drop_column('recipes', 'min_serving_size')
    op.drop_column('recipes', 'max_serving_size')
    # ### end Alembic commands ###
