"""empty message

Revision ID: caf5d45c557d
Revises: 021bb6f183da
Create Date: 2020-07-03 15:24:58.160436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caf5d45c557d'
down_revision = '021bb6f183da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'utilities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'utilities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###
