"""empty message

Revision ID: e520b8b6427e
Revises: 
Create Date: 2020-07-01 10:46:33.696788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import citext

# revision identifiers, used by Alembic.
revision = 'e520b8b6427e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', citext.CIText(), nullable=False),
    sa.Column('password', citext.CIText(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('first_name', citext.CIText(), nullable=False),
    sa.Column('last_name', citext.CIText(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_jwts',
    sa.Column('user_jwt_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('jwt', citext.CIText(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_jwt_id'),
    sa.UniqueConstraint('user_jwt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_jwts')
    op.drop_table('users')
    # ### end Alembic commands ###
