"""empty message

Revision ID: ecef829b81bb
Revises: caf5d45c557d
Create Date: 2020-07-08 14:35:26.467881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import citext

# revision identifiers, used by Alembic.
revision = 'ecef829b81bb'
down_revision = 'caf5d45c557d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_reviews',
    sa.Column('recipe_review_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rating', sa.NUMERIC(), nullable=False),
    sa.Column('review', citext.CIText(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_review_id'),
    sa.UniqueConstraint('recipe_review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_reviews')
    # ### end Alembic commands ###
